CREATE TABLE TestTable(
ID INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE COMMENT 'unique identifier',
KEY1 VARCHAR(50) NOT NULL,
KEY2 VARCHAR(50) NOT NULL,
PRIMARY KEY (ID),
INDEX(ID));


INSERT INTO TestTable (KEY1,KEY2) VALUES('Hello','World');
